Prevent swallowing errors from imported protobufs
Previously, when parsing in synchronous mode (e.g., via the pbjs CLI),
syntax errors in imported files would be swallowed. Protobuf compilation
would then proceed with partial type information, resulting in very
confusing error messages. For example, consider the following protobuf
files:

    # a.proto
    import "b.proto";

    message A {
      B b = 1;
    }

    # b.proto
    ;; syntax error ;;

    message B {
    }

Invoking pbjs on a.proto would fail to report the syntax error in
b.proto, and instead fail with an error like

    Error: no such Type or Enum 'B' in type 'A'

because compilation proceeded by swallowing tye syntax error, without
having parsed the entirety of b.